apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-service
  namespace: noah
  labels:
    app: joke-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-service
  template:
    metadata:
      labels:
        app: joke-service
        version: v1
    spec:
      containers:
      - name: joke-service
        image: jia0/joke-service:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: joke-service
  namespace: noah
  labels:
    app: joke-service
spec:
  selector:
    app: joke-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP